/** Studio selection criteria — 50 method templates (agentic + SaaS), extensible */

export type MethodFamily = "agentic" | "saas" | "ops" | "multimodal";

export interface StudioMethod {
  id: string;
  name: string;
  family: MethodFamily;
  moduleHint: number; // suggested node count band start
  moduleMax: number;
  purpose: string;
  onByDefault: boolean;
  idleSeconds: number;
  clickTrigger: boolean;
  explain: string;
  nextObjective?: string;
}

export const STUDIO_METHODS: StudioMethod[] = [
  {
    id: "m01",
    name: "Spark pair",
    family: "agentic",
    moduleHint: 2,
    moduleMax: 3,
    purpose: "Minimal ReAct loop",
    onByDefault: true,
    idleSeconds: 0,
    clickTrigger: true,
    explain: "Two–three modules: trigger → tool → respond. Ideal for smoke tests.",
    nextObjective: "m05",
  },
  {
    id: "m02",
    name: "Tool triad",
    family: "agentic",
    moduleHint: 3,
    moduleMax: 5,
    purpose: "Planner + tools + verifier",
    onByDefault: true,
    idleSeconds: 30,
    clickTrigger: false,
    explain: "Adds a verifier gate so bad tool outputs fail closed.",
    nextObjective: "m08",
  },
  {
    id: "m03",
    name: "RAG desk",
    family: "agentic",
    moduleHint: 4,
    moduleMax: 8,
    purpose: "Retrieve → ground → answer",
    onByDefault: true,
    idleSeconds: 60,
    clickTrigger: true,
    explain: "Grounded Q&A with citation transform before notify.",
  },
  {
    id: "m04",
    name: "Supervisor handoff",
    family: "agentic",
    moduleHint: 5,
    moduleMax: 12,
    purpose: "Multi-agent handoff",
    onByDefault: false,
    idleSeconds: 120,
    clickTrigger: false,
    explain: "Supervisor delegates to specialist agents with shared memory write.",
    nextObjective: "m15",
  },
  {
    id: "m05",
    name: "Self-heal retry",
    family: "ops",
    moduleHint: 3,
    moduleMax: 6,
    purpose: "Circuit break + heal",
    onByDefault: true,
    idleSeconds: 15,
    clickTrigger: false,
    explain: "Wraps flaky HTTP with selfHeal and backoff delay.",
  },
  {
    id: "m06",
    name: "Checkout recover",
    family: "saas",
    moduleHint: 6,
    moduleMax: 14,
    purpose: "Abandon cart heal",
    onByDefault: true,
    idleSeconds: 300,
    clickTrigger: false,
    explain: "Webhook abandon → field heal → Stripe retry → Slack ops.",
    nextObjective: "m12",
  },
  {
    id: "m07",
    name: "Onboarding lane",
    family: "saas",
    moduleHint: 5,
    moduleMax: 10,
    purpose: "Signup → activate",
    onByDefault: true,
    idleSeconds: 0,
    clickTrigger: true,
    explain: "Auth callback, profile seed, welcome notify, tier gate check.",
  },
  {
    id: "m08",
    name: "Price auditor",
    family: "ops",
    moduleHint: 2,
    moduleMax: 4,
    purpose: "Copy vs tiers.ts",
    onByDefault: true,
    idleSeconds: 86400,
    clickTrigger: false,
    explain: "Cron-aligned: diff public pricing strings against billing SSOT.",
  },
  {
    id: "m09",
    name: "Community seed",
    family: "saas",
    moduleHint: 3,
    moduleMax: 5,
    purpose: "Curator draft post",
    onByDefault: false,
    idleSeconds: 86400,
    clickTrigger: false,
    explain: "Generate moderated draft; human approve before publish.",
  },
  {
    id: "m10",
    name: "Vision intake",
    family: "multimodal",
    moduleHint: 4,
    moduleMax: 9,
    purpose: "Image classify pipeline",
    onByDefault: true,
    idleSeconds: 45,
    clickTrigger: true,
    explain: "Upload → vision classify → route by label → store.",
  },
  {
    id: "m11",
    name: "Voice brief",
    family: "multimodal",
    moduleHint: 4,
    moduleMax: 8,
    purpose: "STT → summarize",
    onByDefault: true,
    idleSeconds: 20,
    clickTrigger: true,
    explain: "Speech-to-text, LLM summary, optional Slack push.",
  },
  {
    id: "m12",
    name: "Marketplace list",
    family: "saas",
    moduleHint: 5,
    moduleMax: 11,
    purpose: "Fee-aware listing",
    onByDefault: true,
    idleSeconds: 0,
    clickTrigger: true,
    explain: "Validates 10+10 fee preview before listing graph for sale.",
  },
  {
    id: "m13",
    name: "Tier gate probe",
    family: "ops",
    moduleHint: 2,
    moduleMax: 3,
    purpose: "Lock Pro routes",
    onByDefault: true,
    idleSeconds: 3600,
    clickTrigger: false,
    explain: "Synthetic checks that gated paths still require Builder/Pro.",
  },
  {
    id: "m14",
    name: "Security inspect",
    family: "ops",
    moduleHint: 3,
    moduleMax: 7,
    purpose: "Auth anomaly scan",
    onByDefault: true,
    idleSeconds: 600,
    clickTrigger: false,
    explain: "Login health + security_events rollup for admin console.",
  },
  {
    id: "m15",
    name: "Monster pipeline",
    family: "agentic",
    moduleHint: 25,
    moduleMax: 50,
    purpose: "Enterprise scale graph",
    onByDefault: false,
    idleSeconds: 90,
    clickTrigger: false,
    explain: "25–50 modules with autonomous next-objective edges.",
  },
  {
    id: "m16",
    name: "Webhook fan-in",
    family: "ops",
    moduleHint: 4,
    moduleMax: 10,
    purpose: "Multi-source ingest",
    onByDefault: true,
    idleSeconds: 10,
    clickTrigger: false,
    explain: "Normalize payloads then branch conditions.",
  },
  {
    id: "m17",
    name: "Human approve gate",
    family: "agentic",
    moduleHint: 3,
    moduleMax: 6,
    purpose: "Fail-safe pause",
    onByDefault: true,
    idleSeconds: 0,
    clickTrigger: true,
    explain: "Blocks autonomous publish until admin clicks approve.",
  },
  {
    id: "m18",
    name: "Overview grade",
    family: "ops",
    moduleHint: 2,
    moduleMax: 4,
    purpose: "Score before ship",
    onByDefault: true,
    idleSeconds: 0,
    clickTrigger: true,
    explain: "Runs overview score; fails deploy under threshold.",
  },
  {
    id: "m19",
    name: "Notify digest",
    family: "saas",
    moduleHint: 3,
    moduleMax: 6,
    purpose: "Batch alerts",
    onByDefault: false,
    idleSeconds: 3600,
    clickTrigger: false,
    explain: "Hourly digest instead of noisy per-event pings.",
  },
  {
    id: "m20",
    name: "Competitor note",
    family: "ops",
    moduleHint: 2,
    moduleMax: 5,
    purpose: "Allowlisted digest",
    onByDefault: false,
    idleSeconds: 604800,
    clickTrigger: false,
    explain: "Scout agent weekly summary from competitive-intelligence docs.",
  },
  {
    id: "m21",
    name: "SEO draft pack",
    family: "saas",
    moduleHint: 3,
    moduleMax: 5,
    purpose: "Title/meta proposals",
    onByDefault: false,
    idleSeconds: 86400,
    clickTrigger: false,
    explain: "Beacon proposes SEO strings; never auto-commits.",
  },
  {
    id: "m22",
    name: "Social kit refresh",
    family: "saas",
    moduleHint: 4,
    moduleMax: 8,
    purpose: "Share cards",
    onByDefault: false,
    idleSeconds: 259200,
    clickTrigger: false,
    explain: "Refresh /resources/social quote + OG assets.",
  },
  {
    id: "m23",
    name: "Analytics rollup",
    family: "ops",
    moduleHint: 3,
    moduleMax: 6,
    purpose: "Visits & flows",
    onByDefault: true,
    idleSeconds: 86400,
    clickTrigger: false,
    explain: "Daily counters for admin analytics dashboard.",
  },
  {
    id: "m24",
    name: "Telemetry stream",
    family: "ops",
    moduleHint: 3,
    moduleMax: 7,
    purpose: "Live event pipe",
    onByDefault: true,
    idleSeconds: 5,
    clickTrigger: false,
    explain: "Thin-outline telemetry for agent console.",
  },
  {
    id: "m25",
    name: "Code export panel",
    family: "agentic",
    moduleHint: 2,
    moduleMax: 50,
    purpose: "Side-panel codegen",
    onByDefault: true,
    idleSeconds: 0,
    clickTrigger: true,
    explain: "As modules attach, highlight generated JS for copy/download.",
  },
  {
    id: "m26",
    name: "Idle timeout park",
    family: "ops",
    moduleHint: 2,
    moduleMax: 3,
    purpose: "Park unused nodes",
    onByDefault: true,
    idleSeconds: 600,
    clickTrigger: false,
    explain: "Marks modules idle after N seconds without fire.",
  },
  {
    id: "m27",
    name: "Click path CTA",
    family: "saas",
    moduleHint: 3,
    moduleMax: 5,
    purpose: "UI click triggers",
    onByDefault: true,
    idleSeconds: 0,
    clickTrigger: true,
    explain: "Binds marketing CTA clicks into workflow start.",
  },
  {
    id: "m28",
    name: "Upsell cadence",
    family: "saas",
    moduleHint: 2,
    moduleMax: 4,
    purpose: "Popup frequency",
    onByDefault: true,
    idleSeconds: 1800,
    clickTrigger: false,
    explain: "Herald tunes UpsellPopupHost caps per session.",
  },
  {
    id: "m29",
    name: "Legal calendar ping",
    family: "ops",
    moduleHint: 2,
    moduleMax: 3,
    purpose: "Counsel reminders",
    onByDefault: false,
    idleSeconds: 2592000,
    clickTrigger: false,
    explain: "Monthly checklist against docs/business-legal.",
  },
  {
    id: "m30",
    name: "Dependency advisory",
    family: "ops",
    moduleHint: 2,
    moduleMax: 4,
    purpose: "Package hygiene",
    onByDefault: false,
    idleSeconds: 604800,
    clickTrigger: false,
    explain: "Notes outdated advisories for maintainers.",
  },
  {
    id: "m31",
    name: "Media remix",
    family: "multimodal",
    moduleHint: 5,
    moduleMax: 12,
    purpose: "Image+video compose",
    onByDefault: false,
    idleSeconds: 60,
    clickTrigger: true,
    explain: "Slideshow + short clip assembly for social kits.",
  },
  {
    id: "m32",
    name: "Storage vault write",
    family: "ops",
    moduleHint: 3,
    moduleMax: 6,
    purpose: "Durable artifact",
    onByDefault: true,
    idleSeconds: 0,
    clickTrigger: false,
    explain: "Writes designs to IndexedDB / server store — not ephemeral disk.",
  },
  {
    id: "m33",
    name: "Stripe portal loop",
    family: "saas",
    moduleHint: 4,
    moduleMax: 8,
    purpose: "Billing self-serve",
    onByDefault: true,
    idleSeconds: 0,
    clickTrigger: true,
    explain: "Customer portal open → webhook sync → tier refresh.",
  },
  {
    id: "m34",
    name: "Enterprise fee path",
    family: "saas",
    moduleHint: 3,
    moduleMax: 6,
    purpose: "12% marketplace",
    onByDefault: false,
    idleSeconds: 0,
    clickTrigger: false,
    explain: "Enterprise negotiated take-rate path.",
  },
  {
    id: "m35",
    name: "Memory reverse snap",
    family: "agentic",
    moduleHint: 3,
    moduleMax: 5,
    purpose: "Reverse memory write",
    onByDefault: true,
    idleSeconds: 120,
    clickTrigger: false,
    explain: "Snapshots prior state for rollback learning.",
  },
  {
    id: "m36",
    name: "Future memory hint",
    family: "agentic",
    moduleHint: 3,
    moduleMax: 5,
    purpose: "Forward plan cache",
    onByDefault: false,
    idleSeconds: 300,
    clickTrigger: false,
    explain: "Stores predicted next objectives for agents.",
  },
  {
    id: "m37",
    name: "Python worker call",
    family: "ops",
    moduleHint: 3,
    moduleMax: 7,
    purpose: "HMAC Python ops",
    onByDefault: true,
    idleSeconds: 0,
    clickTrigger: false,
    explain: "Allowlisted workers/resync_ops with signed requests.",
  },
  {
    id: "m38",
    name: "Cron orchestra",
    family: "ops",
    moduleHint: 4,
    moduleMax: 9,
    purpose: "Schedule coordination",
    onByDefault: true,
    idleSeconds: 3600,
    clickTrigger: false,
    explain: "price-audit, login-health, community-draft sequencing.",
  },
  {
    id: "m39",
    name: "Narrator digest",
    family: "ops",
    moduleHint: 2,
    moduleMax: 4,
    purpose: "Overseer summary",
    onByDefault: true,
    idleSeconds: 3600,
    clickTrigger: false,
    explain: "Site-wide production narrative for admin.",
  },
  {
    id: "m40",
    name: "Module doc explain",
    family: "agentic",
    moduleHint: 2,
    moduleMax: 50,
    purpose: "In-depth purpose text",
    onByDefault: true,
    idleSeconds: 0,
    clickTrigger: true,
    explain: "Shows hundreds of catalog explanations in studio.",
  },
  {
    id: "m41",
    name: "Random module mix",
    family: "agentic",
    moduleHint: 10,
    moduleMax: 20,
    purpose: "2–3 core + expansion",
    onByDefault: false,
    idleSeconds: 45,
    clickTrigger: false,
    explain: "Starts with 2–3 necessary modules then expands 10→20→30→50.",
  },
  {
    id: "m42",
    name: "Partner vault sync",
    family: "ops",
    moduleHint: 2,
    moduleMax: 3,
    purpose: "Private pack only",
    onByDefault: false,
    idleSeconds: 0,
    clickTrigger: false,
    explain: "Never exposes partner materials on public SaaS chrome.",
  },
  {
    id: "m43",
    name: "QR brand stamp",
    family: "saas",
    moduleHint: 2,
    moduleMax: 3,
    purpose: "Deep-link assets",
    onByDefault: true,
    idleSeconds: 0,
    clickTrigger: true,
    explain: "Uses /icons QR + logo on social landings.",
  },
  {
    id: "m44",
    name: "Circuit diag overlay",
    family: "multimodal",
    moduleHint: 2,
    moduleMax: 4,
    purpose: "Infographic backdrop",
    onByDefault: true,
    idleSeconds: 0,
    clickTrigger: false,
    explain: "SVG circuitry motif for developer aesthetic pages.",
  },
  {
    id: "m45",
    name: "Folding chip loop",
    family: "saas",
    moduleHint: 1,
    moduleMax: 2,
    purpose: "Hero motion",
    onByDefault: true,
    idleSeconds: 0,
    clickTrigger: false,
    explain: "FoldingChipBackdrop continuous fold animation.",
  },
  {
    id: "m46",
    name: "Typewriter slogan",
    family: "saas",
    moduleHint: 1,
    moduleMax: 2,
    purpose: "Letter-by-letter UX",
    onByDefault: true,
    idleSeconds: 0,
    clickTrigger: false,
    explain: "Vision quote typewriter on landing.",
  },
  {
    id: "m47",
    name: "Context info mesh",
    family: "saas",
    moduleHint: 2,
    moduleMax: 8,
    purpose: "Help icons",
    onByDefault: true,
    idleSeconds: 0,
    clickTrigger: true,
    explain: "Angled / coloured / underlined ContextInfo placements.",
  },
  {
    id: "m48",
    name: "Admin deny report",
    family: "ops",
    moduleHint: 2,
    moduleMax: 4,
    purpose: "Unauthorized block",
    onByDefault: true,
    idleSeconds: 0,
    clickTrigger: false,
    explain: "Middleware deny → security_events ASAP.",
  },
  {
    id: "m49",
    name: "Studio Agentic lane",
    family: "agentic",
    moduleHint: 8,
    moduleMax: 30,
    purpose: "Studio section A",
    onByDefault: true,
    idleSeconds: 0,
    clickTrigger: true,
    explain: "Dedicated agentic workflow creator in Studio.",
  },
  {
    id: "m50",
    name: "Studio SaaS lane",
    family: "saas",
    moduleHint: 8,
    moduleMax: 30,
    purpose: "Studio section B",
    onByDefault: true,
    idleSeconds: 0,
    clickTrigger: true,
    explain: "Dedicated SaaS product/growth graph section.",
    nextObjective: "m15",
  },
];

export function methodsByFamily(family: MethodFamily): StudioMethod[] {
  return STUDIO_METHODS.filter((m) => m.family === family);
}
